In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[48, 38, 31, 26],
       [97, 71, 60, 29],
       [67, 78,  4, 91],
       [61, 61, 39,  7],
       [72, 35,  1, 41],
       [41, 32, 87, 47]], dtype=int32)

In [3]:
np.sort(a)[::-1]

array([96, 69, 60, 59, 56, 55, 48, 30, 27, 25, 24, 18,  7,  6,  4],
      dtype=int32)

In [4]:
np.sort(b,axis=0)

array([[41, 32,  1,  7],
       [48, 35,  4, 26],
       [61, 38, 31, 29],
       [67, 61, 39, 41],
       [72, 71, 60, 47],
       [97, 78, 87, 91]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 69,   6,  18,  55,  27,  60,  59,  25,  24,   7,  56,   4,  30,
        96,  48, 200])

In [6]:
b

array([[48, 38, 31, 26],
       [97, 71, 60, 29],
       [67, 78,  4, 91],
       [61, 61, 39,  7],
       [72, 35,  1, 41],
       [41, 32, 87, 47]], dtype=int32)

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[4.80000000e+01, 3.80000000e+01, 3.10000000e+01, 2.60000000e+01,
        7.68727356e-01],
       [9.70000000e+01, 7.10000000e+01, 6.00000000e+01, 2.90000000e+01,
        2.15268673e-01],
       [6.70000000e+01, 7.80000000e+01, 4.00000000e+00, 9.10000000e+01,
        7.23590783e-01],
       [6.10000000e+01, 6.10000000e+01, 3.90000000e+01, 7.00000000e+00,
        4.49315621e-02],
       [7.20000000e+01, 3.50000000e+01, 1.00000000e+00, 4.10000000e+01,
        1.27555898e-02],
       [4.10000000e+01, 3.20000000e+01, 8.70000000e+01, 4.70000000e+01,
        6.27026491e-02]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[69],
       [ 6],
       [18],
       [55],
       [27],
       [60],
       [59],
       [25],
       [24],
       [ 7],
       [56],
       [ 4],
       [30],
       [96],
       [48]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  3,  5,  6, 10, 13]),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  6, 18,  0, 27,  0,  0, 25, 24,  7,  0,  4, 30,  0, 48],
      dtype=int32)

In [19]:
np.where(a%2 == 0,0,a)

array([69,  0,  0, 55, 27,  0, 59, 25,  0,  7,  0,  0,  0,  0,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [21]:
# code
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [22]:
np.argmax(a)

np.int64(13)

In [23]:
b

array([[48, 38, 31, 26],
       [97, 71, 60, 29],
       [67, 78,  4, 91],
       [61, 61, 39,  7],
       [72, 35,  1, 41],
       [41, 32, 87, 47]], dtype=int32)

In [24]:
np.argmax(b,axis=0)

array([1, 2, 5, 2])

In [25]:
np.argmax(b,axis=1)

array([0, 0, 3, 0, 0, 2])

In [26]:
# np.argmin
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [28]:
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [29]:
np.cumsum(a)

array([ 69,  75,  93, 148, 175, 235, 294, 319, 343, 350, 406, 410, 440,
       536, 584])

In [30]:
b

array([[48, 38, 31, 26],
       [97, 71, 60, 29],
       [67, 78,  4, 91],
       [61, 61, 39,  7],
       [72, 35,  1, 41],
       [41, 32, 87, 47]], dtype=int32)

In [31]:
np.cumsum(b,axis=1)

array([[ 48,  86, 117, 143],
       [ 97, 168, 228, 257],
       [ 67, 145, 149, 240],
       [ 61, 122, 161, 168],
       [ 72, 107, 108, 149],
       [ 41,  73, 160, 207]])

In [32]:
np.cumsum(b)

array([  48,   86,  117,  143,  240,  311,  371,  400,  467,  545,  549,
        640,  701,  762,  801,  808,  880,  915,  916,  957,  998, 1030,
       1117, 1164])

In [33]:
# np.cumprod
np.cumprod(a)

array([                  69,                  414,                 7452,
                     409860,             11066220,            663973200,
                39174418800,         979360470000,       23504651280000,
            164532558960000,     9213823301760000,    36855293207040000,
        1105658796211200000, -4537220005982109696,  3574368597373353984])

In [34]:
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [36]:
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [37]:
np.percentile(a,50)


np.float64(30.0)

In [38]:
np.median(a)

np.float64(30.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [39]:
# code
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [40]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [41]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [42]:
#code
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [43]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([60, 30], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [44]:
# code
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [45]:
np.flip(a)

array([48, 96, 30,  4, 56,  7, 24, 25, 59, 60, 27, 55, 18,  6, 69],
      dtype=int32)

In [46]:
b

array([[48, 38, 31, 26],
       [97, 71, 60, 29],
       [67, 78,  4, 91],
       [61, 61, 39,  7],
       [72, 35,  1, 41],
       [41, 32, 87, 47]], dtype=int32)

In [47]:
np.flip(b,axis=1)

array([[26, 31, 38, 48],
       [29, 60, 71, 97],
       [91,  4, 78, 67],
       [ 7, 39, 61, 61],
       [41,  1, 35, 72],
       [47, 87, 32, 41]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [48]:
# code
a

array([69,  6, 18, 55, 27, 60, 59, 25, 24,  7, 56,  4, 30, 96, 48],
      dtype=int32)

In [49]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [50]:
# code
a

array([110, 530,  18,  55,  27,  60,  59,  25,  24,   7,  56,   4,  30,
        96,  48], dtype=int32)

In [51]:
np.delete(a,[0,2,4])

array([530,  55,  60,  59,  25,  24,   7,  56,   4,  30,  96,  48],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [52]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
np.intersect1d(m,n)

array([3, 4, 5])

In [54]:
np.setdiff1d(n,m)

array([6, 7])

In [55]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [57]:
# m[np.in1d(m,1)]

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [58]:
# code
a

array([110, 530,  18,  55,  27,  60,  59,  25,  24,   7,  56,   4,  30,
        96,  48], dtype=int32)

In [59]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 55, 27, 60, 59, 25, 25, 25, 56, 25, 30, 75, 48],
      dtype=int32)

In [60]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 55, 27, 60, 59, 25, 25, 25, 56, 25, 30, 75, 48],
      dtype=int32)

In [ ]:
# 17. np.swapaxes

In [61]:
# 18. np.uniform